### ISSUE TITLE
Enable parties to delegate stake for others

### ISSUE THREAD

**Issue by isaacdoidge** [Entropy-Foundation/aptos-core#117]
As a user, I want to be able to delegate stake on behalf of others. I would like to achieve this via a function that looks similar to the below:

`public entry fun add_delegators(funder: &signer, delegator_addresses: vector<address>, principle_stakes: vector<u64>)`

`delegator_addresses` should specify the addresses for which the amount specified at the corresponding index of `principle_stakes` should be delegated. The sum of `principle_stakes` should be deducted from my account.

**Comment by sjoshisupra** [comment]
Fixed in #118
