### ISSUE TITLE
No Active Validators detected after initialization of PBO delegation pools

### ISSUE THREAD

**Issue by supra-yoga** [Entropy-Foundation/aptos-core#34]
After the initialization of PBO delegation pools, querying for the active set of validators returns an empty set. Debugging this with Dr. @sjoshisupra revealed that we need to invoke the `stake::on_new_epoch()` smart contract function at the end of the genesis workflow.

**Comment by sjoshisupra** [comment]
Fixed in PR (https://github.com/Entropy-Foundation/aptos-core/pull/39)
