### ISSUE TITLE
Missing early termination conditions in `pbo_delegation_pool.move:can_principle_unlock`

### ISSUE THREAD

**Issue by isaacdoidge** [Entropy-Foundation/aptos-core#74]
Version: `aptosvm-v1.16_supra-v0.4.2`

The function mentioned in the issue title results in an "execution limit reached" (`4030`) error when the VM is initialized with a timestamp of `0`. We can expect this error to be raised for more recent start times as well.  The problem is that if the number of unlock periods that have passed is very large, then the loop will continue to run despite not having any meaningful work to do. 

The loop should break when the cumulative fraction reaches `1`. Likewise the function should return early if this value is already `1` when it is invoked.

![image](https://github.com/user-attachments/assets/b9e7a7fb-cbec-4e8a-ac9b-4656352941bf)

**Comment by isaacdoidge** [comment]
Addressed by #73.

**Comment by sjoshisupra** [comment]
fixed in #73
