### ISSUE TITLE
Rename `assert_account_is_registered_for_apt` with `assert_account_is_registered_for_supra`

### ISSUE THREAD

**Issue by ghost** [Entropy-Foundation/aptos-core#90]
replace `assert_account_is_registered_for_apt` with `assert_account_is_registered_for_supra` everywhere in the code base and address it in a separate PR.

_Originally posted by @sjoshisupra in https://github.com/Entropy-Foundation/aptos-core/pull/82#discussion_r1782334313_

**Comment by sjoshisupra** [comment]
fixed in #93
