### ISSUE TITLE
`VestEvent` event emits with `next_period_to_vest` as `period_vested`

### ISSUE THREAD

**Issue by vpanchal-supra** [Entropy-Foundation/aptos-core#96]
Right now when any amount is vested using `vest_individual` method `VestEvent` event gets emitted with `next_period_to_vest` as `period_vested` and due to this `period_vested` attribute contains [future](https://github.com/Entropy-Foundation/aptos-core/blob/dev/aptos-move/framework/supra-framework/sources/vesting_without_staking.move#L423) `period_vested`

**Comment by isaacdoidge** [comment]
Good catch @vpanchal-supra.
